#!/bin/dash
#=======================================================================
# File:      sch-magic-num-find
# Created:   17/10/2014
# Purpose:   Search for instance of specified magic-num in specified
#            directory. If found, place filespec and linenumber on stdout.
# See also:  sch-magic-num-generate
# Author:    Bill Cane
# Email:     schoonerdemo@gmail.com
# Copyright: © Bill Cane
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#=======================================================================

usage()
{
cat << EOF
NAME
       sch-magic-num-find - Search for instance of 5-digit magic-num 
       in /usr/bin/sch-*. If found, report linenumber and filespec on stdout. 
       Search is non-recursive at present as that seems more convenient.

SYNOPSIS
       sch-magic-num [5-DIGIT-NUM]

EXIT STATUS
       0      If file containing magic number found.
       1      If no such file found.
       stdout <filespec><" line "><line-num> if file found, otherwise null

USAGE

EOF
}

MagicNum="$1"; FileSpec=''; Problem=''; LineNum=''

[ "$MagicNum" != '' ] || { echo "missing argument"; exit 1; }

# TODO: validate that MagicNum is indeed a 5-digit number

FileSpec="$(grep --line-number $MagicNum /usr/bin/sch-* |head -n1 |cut -d: -f1)"
LineNum="$(grep --line-number $MagicNum /usr/bin/sch-* |head -n1 |cut -d: -f2)"
echo "$FileSpec line $LineNum"
[ "$LineNum" != '' ] || exit 1
exit 0




