#!/bin/dash 
#=======================================================================
# File:      sch-magic-num-to-clipboard
# Created:   12/07/2015
# Purpose:   generate a random 5-digit magic number for insertion into
#            a script as an error tracker and place it on clipboard
# Author:    Bill Cane   
# Email:     
# Copyright: © Bill Cane
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#=======================================================================

# for speed, don't check that generated magic number is unique
sch-clipboard -s "$(tr -c -d 0-9 < /dev/urandom | head -c 5)"

