#!/bin/dash
#=======================================================================
# File:      sch-magic-num
# Created:   17/10/2014
# Purpose:   Utilities for handling magic numbers in scg scripts
# Author:    Bill Cane
# Email:     schoonerdemo@gmail.com
# Copyright: © Bill Cane
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#=======================================================================

usage()
{
cat << EOF
NAME
       sch-magic-num - Utilities for handling magic numbers in code

SYNOPSIS
       sch-magic-num [OPTION]... [FILE]...

DESCRIPTION
	-g generate
			Places 5-digit random magic number on clipboard.

	-f find <magic-num>
			find file containing a magic number and what line it is on.

		valid combinations are:-
		-g
		-f  <magic-num>

EXIT STATUS
       0      -g: always. -f: when file found.
       1      -g: never.  -f: when no file found.
       stdout -g: null.   -f: <filespec><" line "><line-no>

USAGE

EOF
}

find_location()
# Purpose:     search for instance of specified magic-num in specified
#              directory. If found, place filespec and linenumber on stdout.
# Args:        $1:magic-num
# Exit status: 0:found instance
#              1:nothing found
# StdOut:      <line-no><space><filespec>
{
        # to speed things up, we don't check for duplicate magic numbers
	local MagicNum; MagicNum="$1"
	local FileSpec; 
	local LineNum
	[ "$1" != '' ] || { echo "missing argument"; exit 1; }
	
	FileSpec="$(grep --line-number $MagicNum /usr/bin/sch* |head -n1 |cut -d: -f1)"
	LineNum="$(grep --line-number $MagicNum /usr/bin/sch* |head -n1 |cut -d: -f2)"
        echo "$FileSpec line $LineNum"

}

MagicNum="$1";

# process options and args

while getopts "gf:" Option
do
	case "$Option" in
		g )    sch-clipboard -s "$(tr -c -d 0-9 < /dev/urandom | head -c 5)" ;;

		f )	find_location "$MagicNum" ;;

		* ) usage; exit 1 ;;
	esac
done


