#!/bin/dash
. /usr/bin/sch-includes
# File:      sch-backup-git-scripts
# Created:   24/09/2014
# Purpose:   Backup git schooner scripts assuming they are in specified dir
# Author:    Bill Cane
# Email:     schoonerdemo@gmail.com
# Copyright: © Bill Cane
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


local_backup "$HOME/git-repos/schooner/scripts" 'git-schooner-scripts' 
#dlg_show_text "Local Backup" "Examine this file" "filelight" "/home/schdev/Desktop/List Of Actions" 
#dlg_show_text "Local Backup" "Examine this file" "filelight" "/home/schdev/Desktop/Pigeon-sound-2.mp3"
