#!/bin/dash
# File:      sch-servicemenu-actions-image-resize
# Created:   28/06/2015
# Author:
# Email:     schoonerdemo@gmail.com
# Copyright: ©
#
# Licence: This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
. /usr/bin/sch-include

# parameters: $1=suffix-of-target-format $2=input-file
readonly Caption="$(gettext 'Actions For Images')"
readonly Icon='transform-scale'
readonly InFile=$(basename "$2")
readonly OutFile="$InFile.$1"
readonly Notify1=$(gettext "Converting file to different format")
readonly Notify2=$(gettext "File converted to different format")
sch-dlg-notify -c "$Caption" -n "$Notify1" "$Icon" 20
gm convert "$InFile" "$OutFile"
sch-dlg-notify -c "$Caption" -n "$Notify" "$Icon" 5




